### ISSUE TITLE
huge memory consumption for big number of examples in outlined scenario

### ISSUE THREAD

**Issue by pkrzyzaniak** [gabrielfalcao/lettuce#194]
I've made a very simple 2-step scenario outline (go to an ur> & see if header matches), and provided an extensive amount of examples (over 800). I noticed that lettuce is dying around 270-280 example, due lack of memory - at the moment when it dies it already has almost 2GB of ram - so over 7MB for each example.

I did some experiments and I noticed a simple relation - the more examples you have, the more memory it takes for each example. After doing some investigation it looks that the problem is with deepcopy in core.Step.solve_and_clone - with each example it is cloning the whole Step object, including things like the scenario (and whatever those things are referring to).

I guess the solution is to copy explicitly everything that is necessary, I just don't know what all those necessary things are, so I have problem fixing it by myself :)

**Comment by JoeButler99** [comment]
I'm still seeing this in lettuce==0.2.20  Using a long list of examples, I saw deep copy referenced in stack trace when I exited the run.

Is there any workaround or new version I can use

**Comment by lsh-0** [comment]
Just chiming in with my 'me too' - we have a rather large test suite and it eats up all available ram (4GB+) on our Jenkins installation until it's killed by the kernel and the test segfaults. Very mysterious until I watched it happening through top.
