### ISSUE TITLE
"@before.each_step / @after.each_step" should work with outlines also

### ISSUE THREAD

**Issue by throwable-one** [gabrielfalcao/lettuce#451]
For now "@before.each_step" is only called once (before first step)

**Comment by mroohian** [comment]
this issue is preventing PyCharm from running Scenario Outlines.

/Applications/PyCharm.app/Contents/helpers/pycharm/lettuce_runner.py:67

**Comment by throwable-one** [comment]
Waiting for my pull request to be accepted: https://github.com/gabrielfalcao/lettuce/pull/518
