### ISSUE TITLE
Syntax error on python 3.4

### ISSUE THREAD

**Issue by savingschampion** [gabrielfalcao/lettuce#476]
Python 3.4 no longer accepts this notation
```
except Exception, e:
```
instead it uses:
```
except Exception as e:
```

**Comment by lancelote** [comment]
Same here.

**Comment by victormartin** [comment]
+1

**Comment by nass600** [comment]
Is there any tag with this fix or is pip updated including it?

**Comment by danni** [comment]
@nass600: Consider switching to [Aloe](http://aloe.readthedocs.org/en/latest/), which is a successor of the Lettuce/new-parser branch.

**Comment by nass600** [comment]
Thanks @danni
