### ISSUE TITLE
Updating PyPi for Django 1.8 Compatibility

### ISSUE THREAD

**Issue by sdreher** [gabrielfalcao/lettuce#497]
Are there any plans to update Lettuce on PyPI? I'm upgrading to Django 1.8 and need to pick up this PR specifically: https://github.com/gabrielfalcao/lettuce/pull/483

**Comment by danni** [comment]
@sdreher Consider moving to @koterpillar/aloe, which is more or less compatible with the lettuce/new-parser branch (indeed it's a fork off that) and supports all of your favourite features. It also supports Python 3, Django 1.8, etc. http://aloe.readthedocs.org/en/latest/

**Comment by nikolas** [comment]
version 0.2.21 of lettuce contains that django 1.8 fix.
