### ISSUE TITLE
Django 1.9 - Model class doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by kdani3** [gabrielfalcao/lettuce#509]
Looks like `lettuce.django` is broken with Django 1.9

When putting authored apps that have models in INSTALLED_APPS, `manage.py harvest` says "Model class models.ModelName doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. "

Even though the app is in INSTALLED_APPS and it works fine with DRF, for example.

The error is not triggered by my terrain.py. Traceback attached.
[lettuce_traceback.txt](https://github.com/gabrielfalcao/lettuce/files/79870/lettuce_traceback.txt)

**Comment by nikolas** [comment]
tests are passing on my django 1.9 branch here: https://github.com/gabrielfalcao/lettuce/pull/500
so maybe we should make a test for this problem.
